---
name: File-MMagic
version: 1.24
author: ~
abstract: Guess file type
license: open_source
requires:
  perl: 5.005
provides:
  File::MMagic:
    file: MMagic.pm
    version: 1.24
generated_by: Module::Build version 0.26
